//GuessingGame.js
//17 September 2024
//Author: Ndeye Anta Mbaye
//This code prompts user to guess a mystery number between 1 and 10 generated by the function

function checkNumber(){
    let numberToGuess = Math.floor(Math.random()*10) + 1;
    let numberToCheck = prompt("Enter a number between 1 and 10 to guess the mystery number:")

    while (parseInt(numberToCheck) != numberToGuess){
        if(numberToCheck == null){
            return;
        }
        if(parseInt(numberToCheck)<1 || parseInt(numberToCheck)>10){
            numberToCheck= prompt("Invalid Input! Enter a number between 1 and 10:");
        } else {
            numberToCheck = prompt("Wrong guess, try again!", 0);
        }

    }
    if(numberToCheck == numberToGuess){
        alert("Good job! You guessed the correct number.");
    }
}

